### ISSUE TITLE
Custom view is not displayed when refreshing manually

### ISSUE THREAD

**Issue by javichaques** [SimformSolutionsPvtLtd/SSPullToRefresh#29] opened 2023-03-31 08:30 UTC
Hi, i have implemented a custom refresh view using version 1.5 from library and it works perfectly when swipe but is not visible when call setRefreshing from code.
My custom view is a Constraint layout with a lottie animation and TextView.

In this video you can view when I click the "chip button" the refresh view is not visible.
Thanks!

[pull-to-refresh.webm](https://user-images.githubusercontent.com/6851391/229067267-e3873112-bf21-4504-94f7-d8cc7de0b5d8.webm)

**Comment by nishchal-v** [comment] 2023-04-03 07:39
@javichaques Please find this issue fixed in latest release `1.5.1`

**Comment by javichaques** [comment] 2023-04-03 09:13
Hi @nishchal-v , thanks for quick reply
I just tried the new version and it only shows the loader the first time, the second time I call setRefreshing(true) the loader is not shown

**Comment by nishchal-v** [comment] 2023-04-03 09:30
@javichaques I have found the cause for your issue, I'll fix it with a PR soon.

**Comment by nishchal-v** [comment] 2023-04-03 09:54
@javichaques Let me know whether the issue is resolved or not. Then I'll close this issue.

**Comment by javichaques** [comment] 2023-04-03 10:53
> @javichaques Let me know whether the issue is resolved or not. Then I'll close this issue.

I keep having the same issue

**Comment by nishchal-v** [comment] 2023-04-03 12:51
You can check out the [CustomViewDemo](https://github.com/SimformSolutionsPvtLtd/SSPullToRefresh/tree/feature/CustomViewDemo) branch and run the demo project.
Let me know is the difference in your and mine implementations.

**Comment by javichaques** [comment] 2023-04-03 15:01
It seems that it doesn't work with version 1.5.1, I've tried with the version directly from the commit and it works correctly.
`implementation 'com.github.SimformSolutionsPvtLtd:SSPullToRefresh:d729ad745d'`

**Comment by nishchal-v** [comment] 2023-04-03 15:07
yes, if you use `implementation 'com.github.SimformSolutionsPvtLtd:SSPullToRefresh:main-SNAPSHOT'` it downloads the fixed changes but does not work with tag.
So there are some issue with tag. Most probably this could issue from Jitpack side.

**Comment by javichaques** [comment] 2023-04-03 15:17
> yes, if you use `implementation 'com.github.SimformSolutionsPvtLtd:SSPullToRefresh:main-SNAPSHOT'` it downloads the fixed changes but does not work with tag. So there are some issue with tag. Most probably this could issue from Jitpack side.

I think the problem is because a version with the same tag has been generated, perhaps it should be uploaded to 1.5.2

**Comment by nishchal-v** [comment] 2023-04-03 17:02
The versioning is related to tag and the tag is already moved to latest commit `d729ad7`.
Also the [Jitpack](https://jitpack.io/#SimformSolutionsPvtLtd/SSPullToRefresh) page shows using the same commit hash  `d729ad7` for builds of `1.5.1`.

So fetching `1.5.1` should be downloaded with latest changes.

**Comment by nishchal-v** [comment] 2023-04-03 17:04
Just `Invalidate cache and Restart` Android studio, it would work just fine

**Comment by nishchal-v** [comment] 2023-04-03 18:00
@javichaques Please clear your gradle cache, it should work just fine.
Here is an helpful [SO](https://stackoverflow.com/a/30450020/17633215) answer.

**Closed as completed** 2023-04-03 20:38 UTC
Labels: bug
